# Generated by Django 6.0.7 on 2026-07-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('importados', models.IntegerField(default=0)),
                ('ignorados', models.IntegerField(default=0)),
            ],
        ),
    ]
